### ISSUE TITLE
User not authorized

### ISSUE THREAD

**Issue by jg-mahendra** [financialforcedev/ffhttp-dropbox#2]
Hi Matt, I am getting an error "The connector Dropbox API for User has not been authorized".
This happened when I tried to validate the connection from Test Harness tab.

It would be great if you can help on this.

Thanks,
Mahendra

**Comment by mwoodcertinia** [comment]
Hi Mahendra,

The error "The connector Dropbox API for User has not been authorized" is shown when the corresponding connection has not been activated i.e. the OAuth process has not been invoked for the connection.

From your error message, you should have a Connector (under the Connector tab) named 'Dropbox API for User'. The list view should show an 'active' column. If active is unchecked for this connector you get the error message.

Assuming that everything is configured correctly on the connector and connector type, you should be able to select the connector and click 'Activate', then 'Authorize'. This will guide you through the OAuth process. Upon successful completion the connection will be authorized and you should be able to use the API calls from the test harness.

Thanks,
Matt

**Comment by jg-mahendra** [comment]
Hi Matt,

Thanks a lot, I was able to figure out the problem but when I try again to activate the connection  I am getting the following error. 

Am I missing any particular setting here ?

![capture1](https://cloud.githubusercontent.com/assets/12056281/17548885/83189f5e-5f0b-11e6-9687-146ab0dc2968.PNG)

**Comment by mwoodcertinia** [comment]
No problem.

The Test Harness relies on a _Connector Type_ named 'Dropbox API' and returns this error if it doesn't find it.

If you have an authenticated connector, then the simplest way to get this working is to change the associated connector type name to 'Dropbox API'.

**Comment by jg-mahendra** [comment]
Hi Matt,

I just tried with renaming the connect type but it seems like still its not working.

![capture2](https://cloud.githubusercontent.com/assets/12056281/17550771/44e4c95c-5f14-11e6-9dbc-7137068737b9.PNG)

Thanks,
Mahendra

**Comment by jg-mahendra** [comment]
The connector is not getting activated, I believe that is the problem.
I ran the script from developer console also.

**Comment by mwoodcertinia** [comment]
From the screenshot, it appears that you now have a valid connector type.

It should look something like this (but with your Dropbox App Client Id and Client Secret, together with the appropriate Salesforce instance in the redirect URI (for example, eu5 rather than gs0)) :

<img width="1000" alt="connector type" src="https://cloud.githubusercontent.com/assets/9592432/17556299/ca107ec8-5f0a-11e6-87fa-60d4e27141d6.png">

Given that you have the same error message as earlier, I'm expecting the Connectors list view to look the same as above, i.e. with an inactive connector. 

Select the connector, which must be owned by the user that you are logged in as, then 'Activate':

<img width="400" alt="connector type" src="https://cloud.githubusercontent.com/assets/9592432/17556801/a8406cc0-5f0c-11e6-9a3d-958b77e54160.png">

Then authorise:

<img width="1000" alt="screen shot 2016-08-10 at 13 45 56" src="https://cloud.githubusercontent.com/assets/9592432/17556917/1c58eec0-5f0d-11e6-8c09-b7d74f06d6cc.png">

This is the point that you should be taken through the OAuth process with Dropbox.

After the process is complete you should end up with an authorised connector...
<img width="400" alt="activated connector" src="https://cloud.githubusercontent.com/assets/9592432/17556962/4e766982-5f0d-11e6-8157-06a50d7865e6.png">

and the test harness should show that this connector is being used...
<img width="1194" alt="test harness - approved connector" src="https://cloud.githubusercontent.com/assets/9592432/17556981/5e9c64e2-5f0d-11e6-8e2f-6071c0d156a5.png">

Note that the test harness page does not automatically go through the OAuth process.

**Comment by jg-mahendra** [comment]
Hi Matt,

The Access token was blank that is why the connector was not getting activated. I gave a random number and the connector is now activated.

When I try to move the attachment from the Account "Move Attachment to dropbox" button I am getting following error 

![image](https://cloud.githubusercontent.com/assets/12056281/17588218/ff4da9e0-5fea-11e6-8204-dbc8d9b01790.png)
![capture 1png](https://cloud.githubusercontent.com/assets/12056281/17588231/162a20f8-5feb-11e6-9cf2-a6aa18422cab.PNG)

Thank You,
Mahendra

**Comment by mwoodcertinia** [comment]
Hi Mahendra,

You're getting a Visualforce page error because the OAuth process between Force.com and Dropbox has not been completed. Upon successful completion of the OAuth process, the Access Token and TokenType fields are populated with data required to access the Dropbox APIs found at https://www.dropbox.com/developers-v1/core/docs. I have outlined the steps to populate these fields in my previous post.

Populating the Access Token manually with a random number is incorrect and none of the test harness functions will work correctly by doing this.

Thanks,
Matt

**Comment by jg-mahendra** [comment]
Hi Matt,

The connector type is getting created when I run the script from Salesforce Devolper Console,

but after this when I try to create connector and activate this, It doesn't work for me.
I am pretty sure that I am close but missed some required steps.

Looking forward to hear from you.

Thanks,
Mahendra

**Comment by mwoodcertinia** [comment]
Hi Mahendra,

From your screenshot, the Redirect URI is missing /apex/connector i.e. your redirect URI should be:

https://identityconnectmahendra-dev-ed.my.salesforce.com/apex/connector

This also needs to be set in the OAuth2 redirect URIs section of your Dropbox App.

I've removed your screenshot too as it contained the client id and secret for your Dropbox account.

Thanks,
Matt

**Comment by jg-mahendra** [comment]
Hi Matt,

It's working :)

Thank You for all the kind help ..!!
Great work, keep it up :)
